variables:
  DOCKER_DRIVER: overlay

stages: 
  - test
  - publish

test: 
  image: painless/tox
  stage: test
  script: 
    - tox

publish:
  stage: publish
  image: docker:19.03.1
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - docker build -t gcr.io/master-gke/restaurant:latest .
    - docker push gcr.io/master-gke/restaurant:latest
  only:
    - master