variables:
  DOCKER_DRIVER: overlay

stages: 
  - test
  - publish

lint: 
  image: 
    - python:3.8.1-alpine

  stage: test
  script: 
    - npm ci

publish:
  stage: publish
  image: docker:19.03.1
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcloud-service-key.json
    - docker build -t gcr.io/master-gke/restaurant:latest .
    - docker push gcr.io/master-gke/restaurant:latest
  only:
    - master