---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restaurant-data-volume
  labels:
    app: restaurant

spec:
  storageClass: local-storage
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  hostPath:
    path: /tmp/data