apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-data-claim
spec:
  storageClassName: local-storage
  selector:
    matchLabels:
      app: restaurant
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi