apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - name: main 
      port: 27017
      targetPort: mongodb
      
  selector:
    app: mongodb
