apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb-h
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: mongodb-h
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        envFrom:
          - secretRef:
              name: mongo-secret
        volumeMounts:
          - name: restaurant-pvc
            mountPath: ./mongodb:/data/db

      volumes:
        - name: restaurant-pvc
          persistentVolumeClaim:
            claimName: restaurant-pvc

  selector:
    matchLabels:
      app: mongodb-h

  serviceName: mongodb-h

    