apiVersion: v1
kind: Service
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  type: NodePort
  ports:
    - name: main 
      port: 8080
      targetPort: 8080
      protocol: "TCP"
      
  selector:
    app: restaurant
